### PR TITLE
Remove some generated files and add them to .gitignore

### PR DESCRIPTION
**Pull request by LeonardKoenig**
Issue: #9 

I hope I got them all ;-)

### CODE REVIEW

**Comment by SLAwww** [comment]
In EntitiesMP, there is a Common folder that contains .H and .CPP files that should not be excluded, as they are not automatically generated.

**Comment by LeonardKoenig** [comment]
I'm pretty sure that this'd only ignore *.h / *.cpp that are directly within EntitiesMP (ie. not in all subfolders), so this wouldn't be an issue.
I will test this and add the other files lateron, as I'm currently out of home.

**Comment by LeonardKoenig** [comment]
Yep, confirmed, files in EntitiesMP/Common/{*.h,*.cpp} won't be ignored.
Also I've added *.log and *.rpt files. I consider it ready for merge -- haven't found any more generated files.

**Comment by SLAwww** [comment]
There are many more generated files. Try building entire solution and then commit, then you'll see them.

**Comment by LeonardKoenig** [comment]
no problem ;-)
I built the whole solution but w/o DX SDK etc. as I had them not handy so this could probably be the reason why I hadn't more of those files.

Ecc/Parser.* are also generated using Bison I noticed, although this seems to be broken currently (see here for the issue: #17)

**Pull request closed without merging**
