### PR TITLE
Fix compilation when build path is long

### PR DESCRIPTION
**Pull request by aron1024**
Also remove generated file Parser.cpp

### CODE REVIEW

**Comment by Ragora** [comment]
I always did find it rather peculiar that one of the suggested actions for resolving compile errors was to reduce the length of the file path.

**Comment by SLAwww** [comment]
Finally someone found the cause of that, thank you! But I had to replace snprintf with sprintf because snprintf was not recognized by VS 2013 compiler.

**Comment by aron1024** [comment]
I found the issue because VS 2015 reported a stack overrun in Ecc for certain *.es files in my build - that's why I also switched it to use the safer snprintf. I think all versions of VS have _snprintf instead but apparently that works slightly different than the standard snprintf. Anyway, in this case a buffer size of 512 with sprintf is more than enough for Windows (which enforces a max path length of 260 on every file) and should also suffice for other platforms.

**Comment by gogirl2016** [comment]
Server

**Pull request merged**
