### PR TITLE
SeriousSam(GameExecutable) cleanup and refactoring. (Resolved)

### PR DESCRIPTION
**Pull request by zcaliptium**
- Split Menu.cpp into multiple files.
- Split MenuGadgets and Menus classes into separate files. One file - one class.
- Get rid of tonn of variables like mgOptionsMenuTitleLabel(put them into suitable classes).
- A lot of fixes. Make code more readable. Get rid of useless stuff.
- etc. Comments? No comments!

### CODE REVIEW

**Comment by rcgordon** [comment]
Can we revert this thing where Menu.cpp got split up?

First: there was no value in splitting this file up. It didn't improve its readability, and it wasn't hurting anything.
Second: it increases compile times, since we have to parse all the engine's headers for dozens of little files. There's no reason to have a source file with a single function in it.
Third: All the changes I made in my branch for the Linux port are no longer eligible for merging and conflict resolution, because git sees my work as done to a file that was deleted and doesn't know its contents has just been scattered around into other files.

**Comment by zcaliptium** [comment]
Idk. For me it compiles with the same speed even if I have weak CPU. I see no problems in resolving conflicts. It's so easy.

**Comment by SLAwww** [comment]
First, I do not agree this change doesn't improve readability. People who would later use the engine would not prefer 15k lines of global variables and functions over a nicely organized class system.
Second, entire engine compiles very swiftly on modern machines.
Third, I suggest that you merge the main branch to your one and use updated code from the main branch, because there are recent fixes that address significant problems that were initially present, like online connectivity.
Fourth, I know that you have a huge experience in this field Ryan, but seeing your recent allegations that you made online makes me think you are fundamentally wrong at one point. Serious Engine was not open-sourced for a single purpose of making a Linux port. Every person has a right to try improving the engine. You basically say that they should halt and make way for a Linux port. With all respect to you and your work, unfortunately I can't sacrifice the other people's useful contributions because you have problems merging.

**Comment by rcgordon** [comment]
>  I see no problems in resolving conflicts. It's so easy.

You were right, I found an easy solution.

Thanks,
--ryan.

**Comment by rcgordon** [comment]
> Serious Engine was not open-sourced for a single purpose of making a Linux port.

Of course it wasn't, which is why I listed several other technical concerns first. But I've got thousands and thousands of lines of changes that were necessary and add real value to the codebase, and this change made it harder for me, and while I don't think the world has to bend to my needs, it doesn't make we want to have a little cooperation any less. I've been hand-merging large changes into Serious Engine for _fifteen years_, and it would have been nice to not have to do it one more time.

It would have been nice to not get such an impolite response to my concerns, too.

**Comment by SLAwww** [comment]
The response was as polite as possible, especially in comparison to some of the other statements you made. Changes in the main branch are not "untrustworthy", nor they are "useless", all of them address important problems that affect everybody who uses the engine. I do value your wish to bring Serious Engine to the Linux platform, it's undoubtedly a great mission. In fact, if refactoring is your biggest concern, then you should not worry any more because it's not going to happen in other parts of the engine. But it had to be done in the menu system, actually we should have done that before releasing the sources.

**Comment by rcgordon** [comment]
Hey, I'm sorry if I was being a jerk about this. Obviously we're all working towards the same goals and (mostly, sorry!) cooperating well.

I'll tone down my attitude going forward.

**Comment by SLAwww** [comment]
Thank you. I hope we can have more constructive collaboration eventually.

**Pull request merged**
