### PR TITLE
Fix for Ecc failing on empty files

### PR DESCRIPTION
**Pull request by Ragora**
I feel like this PR will change a little bit as it feels more like a bandaid than an actual fix, but we'll see what the developers say about it. I've tested it with my local builds here and it properly discerns between "empty" files and files that have content in them, where the "empty" files simply return and do nothing. From what @SLAwww said in #11, this is what they wanted without any extra dependencies.

I will note that this does seem to slow down the Ecc executable very slightly, as it takes about 3 or 4 seconds now to rebuild every single Es in the engine directory versus the original instant I had previously.  However, that's with a single thread of commands looping over all the files. If the build process invokes it in individual threads (looping foreach file, invoking Ecc and not waiting on return status versus waiting), then this speed drop should be less noticeable. 

That and this was really only tested on a Linux machine thus far, I've actually got no Windows machine here at all to roll it through at the moment.

### CODE REVIEW

**Comment by SLAwww** [comment]
Performance drop is a bit suspicious, I'm going to test it on my PC and see if everything is okay.

**Comment by Ragora** [comment]
Might easily be something I did wrong or strangely, but this is what peer reviews are for.

**Comment by SLAwww** [comment]
Did you try compiling EntitiesMP? For some reason ECC crashes on some files now. This crash doesn't happen with original ECC.

**Comment by Ragora** [comment]
I'll check that once I work out the performance issue, I just realized a much simpler approach I can take on this. The builds I was doing should've covered everything in the entire engine recursively.

**Comment by Ragora** [comment]
Committed a faster version to the branch. I've retested it and every single Es in the entire engine directly appears to build correctly.

**Comment by SLAwww** [comment]
Everything seems to work fine now, thank you!

**Comment by Ragora** [comment]
I actually don't remember why I did close and reopen, huh. Either way, I've fixed that here and I'll poke about 0 length files right now.

**Pull request merged**
