### PR TITLE
Fixes to issue #25

### PR DESCRIPTION
**Pull request by fobo66**
- Updated project files to VS2015
- Little conditions fixes according to static analyser report at issue #25 
- Only obvious bugs fixed.

### CODE REVIEW

**Comment by SLAwww** [comment]
Project files are meant to be usable in VS2013 and VS2015, there is no need in updating them this way, because as you open the solution in VS2015 all the projects can be automatically updated in a few seconds.

**Comment by Ragora** [comment]
I've seen it just happen transparently with as old as VS2010 I believe.

**Comment by fobo66** [comment]
Alright, can .vcxproj files be converted back to VS2013 when I open the solution in current state with this version of VS?

**Comment by TheLonerD** [comment]
@fobo66 yes (даже 2010 SP1 студия может открыть).

**Comment by fobo66** [comment]
So, what's the problem?

**Comment by yamgent** [comment]
Those people that uses VS2013 will no longer be able to compile the projects if you update them to VS2015 projects.

From my VS2013:
`error MSB8020: The build tools for v140 (Platform Toolset = 'v140') cannot be found. To build using the v140 build tools, please install v140 build tools.  Alternatively, you may upgrade to the current Visual Studio tools by selecting the Project menu or right-click the solution, and then selecting "Upgrade Solution..."`

There was no such button to "upgrade" from 2015 to 2013. Searches on Google so far suggest that I have to manually edit the XML to downgrade to 2013.

**Comment by TheLonerD** [comment]
@yamgent what? On project settings you can change platform toolset to v130. There is no need to manually editing xml project files.

**Comment by SLAwww** [comment]
Either way, VS2013 users will have to manually change project settings in order to build the projects. Why should we complicate things like that? Let's leave the old platform toolset version in the projects, so both VS2013 and VS2015 users can build the solution easily.

**Comment by fobo66** [comment]
Okay, close this PR. I'll send another one later, without .vcxproj modification.

**Pull request closed without merging**
